using System.ComponentModel;
using FlatSharp.Attributes;
// ReSharper disable UnusedMember.Global
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable UnusedType.Global
#nullable disable

namespace pkNX.Structures.FlatBuffers;

// Generated by FlatSharp
// FileIdentifier: 
// FileExtension: 
// Object Count: 13
// Enum Count: 17
// Root Type: DLCItemGroupArray

[FlatBufferTable, TypeConverter(typeof(ExpandableObjectConverter))]
public class DLCItemGroupArray : IFlatBufferArchive<DLCItemGroup>
{
    [FlatBufferItem(0)] public DLCItemGroup[] Table { get; set; }
}

[FlatBufferTable, TypeConverter(typeof(ExpandableObjectConverter))]
public class DLCItemGroup
{
    [FlatBufferItem(0)] public DLCItemType ItemType { get; set; }
    [FlatBufferItem(1)] public int DataId { get; set; }
    [FlatBufferItem(2)] public int SortId { get; set; }
    [FlatBufferItem(3)] public string GroupNameTextLabel { get; set; }
    [FlatBufferItem(4)] public DLCItemGender ItemGender { get; set; }
    [FlatBufferItem(5)] public DLCItemDataList ItemDataList { get; set; }
}

[FlatBufferTable, TypeConverter(typeof(ExpandableObjectConverter))]
public class DLCItemDataList
{
    [FlatBufferItem(00)] public DLCItemData ItemData01 { get; set; }
    [FlatBufferItem(01)] public DLCItemData ItemData02 { get; set; }
    [FlatBufferItem(02)] public DLCItemData ItemData03 { get; set; }
    [FlatBufferItem(03)] public DLCItemData ItemData04 { get; set; }
    [FlatBufferItem(04)] public DLCItemData ItemData05 { get; set; }
    [FlatBufferItem(05)] public DLCItemData ItemData06 { get; set; }
    [FlatBufferItem(06)] public DLCItemData ItemData07 { get; set; }
    [FlatBufferItem(07)] public DLCItemData ItemData08 { get; set; }
    [FlatBufferItem(08)] public DLCItemData ItemData09 { get; set; }
    [FlatBufferItem(09)] public DLCItemData ItemData10 { get; set; }
    [FlatBufferItem(10)] public DLCItemData ItemData11 { get; set; }
    [FlatBufferItem(11)] public DLCItemData ItemData12 { get; set; }
}

[FlatBufferTable, TypeConverter(typeof(ExpandableObjectConverter))]
public class DLCItemData
{
    [FlatBufferItem(0)] public DLCItemType ItemType { get; set; }
    [FlatBufferItem(1)] public ItemID ItemId { get; set; }
    [FlatBufferItem(2)] public int ItemNum { get; set; }
    [FlatBufferItem(3)] public int DressupItemId { get; set; }
    [FlatBufferItem(4)] public PokeDataDLCGift PokemonData { get; set; }
}

[FlatBufferTable, TypeConverter(typeof(ExpandableObjectConverter))]
public class PokeDataDLCGift
{
    [FlatBufferItem(00)] public DevID DevId { get; set; }
    [FlatBufferItem(01)] public short FormId { get; set; }
    [FlatBufferItem(02)] public int Level { get; set; }
    [FlatBufferItem(03)] public SexType Sex { get; set; }
    [FlatBufferItem(04)] public TokuseiType Tokusei { get; set; }
    [FlatBufferItem(05)] public GemType GemType { get; set; }
    [FlatBufferItem(06)] public RareType RareType { get; set; }
    [FlatBufferItem(07)] public SizeType ScaleType { get; set; }
    [FlatBufferItem(08)] public short ScaleValue { get; set; }
    [FlatBufferItem(09)] public SizeType WeightType { get; set; }
    [FlatBufferItem(10)] public short WaightValue { get; set; }
    [FlatBufferItem(11)] public TalentType TalentType { get; set; }
    [FlatBufferItem(12)] public sbyte TalentVnum { get; set; }
    [FlatBufferItem(13)] public ParamSet TalentValue { get; set; }
    [FlatBufferItem(14)] public ParamSet EffortValue { get; set; }
    [FlatBufferItem(15)] public ItemID Item { get; set; }
    [FlatBufferItem(16)] public SeikakuType Seikaku { get; set; }
    [FlatBufferItem(17)] public SeikakuType SeikakuHosei { get; set; }
    [FlatBufferItem(18)] public WazaType WazaType { get; set; }
    [FlatBufferItem(19)] public WazaSet Waza1 { get; set; }
    [FlatBufferItem(20)] public WazaSet Waza2 { get; set; }
    [FlatBufferItem(21)] public WazaSet Waza3 { get; set; }
    [FlatBufferItem(22)] public WazaSet Waza4 { get; set; }
    [FlatBufferItem(23)] public BallType BallId { get; set; }
    [FlatBufferItem(24)] public bool UseNickName { get; set; }
    [FlatBufferItem(25)] public ulong NicknameLabel { get; set; }
    [FlatBufferItem(26)] public SexType ParentSex { get; set; }
}

[FlatBufferEnum(typeof(int))]
public enum DLCItemGender
{
    ALL = 0,
    MALE = 1,
    FEMALE = 2,
}

[FlatBufferEnum(typeof(int))]
public enum DLCItemType
{
    DLCNONE = 0,
    DLCItem = 1,
    DLCDressUpItem = 2,
    DLCPokemon = 3,
}
