using System.ComponentModel;
using FlatSharp.Attributes;
// ReSharper disable UnusedMember.Global
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable UnusedType.Global
#nullable disable

namespace pkNX.Structures.FlatBuffers;

// Generated by FlatSharp
// FileIdentifier: 
// FileExtension: 
// Object Count: 2
// Enum Count: 1
// Root Type: gym.denki.PopupPosTableArray

[FlatBufferTable, TypeConverter(typeof(ExpandableObjectConverter))]
public class PopupPosTableArray : IFlatBufferArchive<PopupPosTable>
{
    [FlatBufferItem(0)] public PopupPosTable[] Table { get; set; }
}

[FlatBufferTable, TypeConverter(typeof(ExpandableObjectConverter))]
public class PopupPosTable
{
    [FlatBufferItem(0)] public int AreaId { get; set; }
    [FlatBufferItem(1)] public int PosId { get; set; }
    [FlatBufferItem(2)] public float PosX { get; set; }
    [FlatBufferItem(3)] public float PosY { get; set; }
    [FlatBufferItem(4)] public WindowType WindowType { get; set; }
}

[FlatBufferEnum(typeof(int))]
public enum WindowType
{
    Normal = 0,
    Burst = 1,
    Thinking = 2,
    SubQuest = 3,
}
