using System.ComponentModel;
using FlatSharp.Attributes;
// ReSharper disable UnusedMember.Global
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable UnusedType.Global
#nullable disable

namespace pkNX.Structures.FlatBuffers;

// Generated by FlatSharp
// FileIdentifier: 
// FileExtension: 
// Object Count: 6
// Enum Count: 1
// Root Type: gym.mushi.GymMushiData

[FlatBufferStruct, TypeConverter(typeof(ExpandableObjectConverter))]
public class SubEventParam
{
    [FlatBufferItem(0)] public ItemID ItemID { get; set; }
    [FlatBufferItem(1)] public int ItemNum { get; set; }
}

[FlatBufferStruct, TypeConverter(typeof(ExpandableObjectConverter))]
public class PushBallPower
{
    [FlatBufferItem(0)] public float Forward { get; set; }
    [FlatBufferItem(1)] public float Upper { get; set; }
    [FlatBufferItem(2)] public float RideForward { get; set; }
    [FlatBufferItem(3)] public float RideUpper { get; set; }
}

[FlatBufferTable, TypeConverter(typeof(ExpandableObjectConverter))]
public class GymMushiData
{
    [FlatBufferItem(0)] public PushBallPower PushBallPower { get; set; }
    [FlatBufferItem(1)] public BoundOutsideFence BoundOutsideFence { get; set; }
    [FlatBufferItem(2)] public float BallStartHeightOffset { get; set; }
    [FlatBufferItem(3)] public FreeMoveParam FreeMoveParam { get; set; }
    [FlatBufferItem(4)] public EventCommonParam EventCommonParam { get; set; }
    [FlatBufferItem(5)] public SubEventParam SubEventParam { get; set; }
}

[FlatBufferStruct, TypeConverter(typeof(ExpandableObjectConverter))]
public class FreeMoveParam
{
    [FlatBufferItem(0)] public float FadeOutTime { get; set; }
    [FlatBufferItem(1)] public float FadeInTime { get; set; }
    [FlatBufferItem(2)] public float GoalBallVelocity { get; set; }
    [FlatBufferItem(3)] public float GoalTimeOut { get; set; }
}

[FlatBufferStruct, TypeConverter(typeof(ExpandableObjectConverter))]
public class EventCommonParam
{
    [FlatBufferItem(0)] public float GoalBallVelocity { get; set; }
    [FlatBufferItem(1)] public float PlayerWaitTime { get; set; }
}

[FlatBufferStruct, TypeConverter(typeof(ExpandableObjectConverter))]
public class BoundOutsideFence
{
    [FlatBufferItem(0)] public float Add { get; set; }
    [FlatBufferItem(1)] public float Magnification { get; set; }
}
