using System.ComponentModel;
using FlatSharp.Attributes;
// ReSharper disable UnusedMember.Global
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable UnusedType.Global
#nullable disable

namespace pkNX.Structures.FlatBuffers;

// Generated by FlatSharp
// FileIdentifier: 
// FileExtension: 
// Object Count: 2
// Enum Count: 1
// Root Type: gym.kusa.PokeTableArray

[FlatBufferTable, TypeConverter(typeof(ExpandableObjectConverter))]
public class PokeTableArray : IFlatBufferArchive<PokeTable>
{
    [FlatBufferItem(0)] public PokeTable[] Table { get; set; }
}

[FlatBufferTable, TypeConverter(typeof(ExpandableObjectConverter))]
public class PokeTable
{
    [FlatBufferItem(00)] public string ObjectName { get; set; }
    [FlatBufferItem(01)] public string FindFlagName { get; set; }
    [FlatBufferItem(02)] public bool IsBattle { get; set; }
    [FlatBufferItem(03)] public string BattleFlagName { get; set; }
    [FlatBufferItem(04)] public string BattleId { get; set; }
    [FlatBufferItem(05)] public string BattleMessageName { get; set; }
    [FlatBufferItem(06)] public string RanchMessageName { get; set; }
    [FlatBufferItem(07)] public Feature Feature { get; set; }
    [FlatBufferItem(08)] public string PositionXFlagName { get; set; }
    [FlatBufferItem(09)] public string PositionYFlagName { get; set; }
    [FlatBufferItem(10)] public string PositionZFlagName { get; set; }
}

[FlatBufferEnum(typeof(int))]
public enum Feature
{
    Stand = 0,
    Hiding = 1,
    Runaway = 2,
    Tree = 3,
    FlowerPot = 4,
    Shopping = 5,
}
