using System.ComponentModel;
using FlatSharp.Attributes;
// ReSharper disable UnusedMember.Global
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable UnusedType.Global
#nullable disable

namespace pkNX.Structures.FlatBuffers;

// Generated by FlatSharp
// FileIdentifier: 
// FileExtension: 
// Object Count: 2
// Enum Count: 1
// Root Type: gym.mushi.GymMushiRewardArray

[FlatBufferTable, TypeConverter(typeof(ExpandableObjectConverter))]
public class GymMushiRewardArray : IFlatBufferArchive<GymMushiReward>
{
    [FlatBufferItem(0)] public GymMushiReward[] Table { get; set; }
}

[FlatBufferTable, TypeConverter(typeof(ExpandableObjectConverter))]
public class GymMushiReward
{
    [FlatBufferItem(0)] public ItemID ItemID { get; set; }
    [FlatBufferItem(1)] public int ItemNum { get; set; }
    [FlatBufferItem(2)] public int ClearTimeMinutes { get; set; }
    [FlatBufferItem(3)] public int ClearTimeSeconds { get; set; }
    [FlatBufferItem(4)] public int ClearTimeMillisecond { get; set; }
    [FlatBufferItem(5)] public string ItemReceivedWorkName { get; set; }
    [FlatBufferItem(6)] public bool IsClear { get; set; }
}
