using System.ComponentModel;
using FlatSharp.Attributes;
// ReSharper disable UnusedMember.Global
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable UnusedType.Global
#nullable disable

namespace pkNX.Structures.FlatBuffers;

// Generated by FlatSharp
// FileIdentifier: 
// FileExtension: 
// Object Count: 5
// Enum Count: 1
// Root Type: gym.esper.EXERCISE_COURSESArray

[FlatBufferTable, TypeConverter(typeof(ExpandableObjectConverter))]
public class EXERCISECOURSESArray : IFlatBufferArchive<EXERCISECOURSES>
{
    [FlatBufferItem(0)] public EXERCISECOURSES[] Table { get; set; }
}

[FlatBufferTable, TypeConverter(typeof(ExpandableObjectConverter))]
public class EXERCISECOURSES
{
    [FlatBufferItem(0)] public ExerciseSetting ExerciseSetting { get; set; }
}
