using System.ComponentModel;
using FlatSharp.Attributes;
// ReSharper disable UnusedMember.Global
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable UnusedType.Global
#nullable disable

namespace pkNX.Structures.FlatBuffers;

// Generated by FlatSharp
// FileIdentifier: 
// FileExtension: 
// Object Count: 2
// Enum Count: 2
// Root Type: gym.mizu.SeriItemTableArray

[FlatBufferTable, TypeConverter(typeof(ExpandableObjectConverter))]
public class SeriItemTableArray : IFlatBufferArchive<SeriItemTable>
{
    [FlatBufferItem(0)] public SeriItemTable[] Table { get; set; }
}

[FlatBufferTable, TypeConverter(typeof(ExpandableObjectConverter))]
public class SeriItemTable
{
    [FlatBufferItem(00)] public int SeriItemTableId { get; set; }
    [FlatBufferItem(01)] public ItemID ItemId { get; set; }
    [FlatBufferItem(02)] public int MinPrice { get; set; }
    [FlatBufferItem(03)] public int BasePrice { get; set; }
    [FlatBufferItem(04)] public int MinItemNum { get; set; }
    [FlatBufferItem(05)] public int MaxItemNum { get; set; }
    [FlatBufferItem(06)] public float DiscountRate { get; set; }
    [FlatBufferItem(07)] public int Venue1Probability { get; set; }
    [FlatBufferItem(08)] public int Venue2Probability { get; set; }
    [FlatBufferItem(09)] public int Venue3Probability { get; set; }
    [FlatBufferItem(10)] public int Venue4Probability { get; set; }
    [FlatBufferItem(11)] public string BarkerMessageLabelName { get; set; }
    [FlatBufferItem(12)] public string ItemObjectName { get; set; }
    [FlatBufferItem(13)] public string BoxObjectName { get; set; }
    [FlatBufferItem(14)] public string EffectName { get; set; }
    [FlatBufferItem(15)] public string AcquiredFlagName { get; set; }
    [FlatBufferItem(16)] public DevID DevId { get; set; }
}
