using System.ComponentModel;
using FlatSharp.Attributes;
// ReSharper disable UnusedMember.Global
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable UnusedType.Global
#nullable disable

namespace pkNX.Structures.FlatBuffers;

// Generated by FlatSharp
// FileIdentifier: 
// FileExtension: 
// Object Count: 2
// Enum Count: 0
// Root Type: gym_denki.PopupFixTableArray

[FlatBufferTable, TypeConverter(typeof(ExpandableObjectConverter))]
public class PopupFixTableArray : IFlatBufferArchive<PopupFixTable>
{
    [FlatBufferItem(0)] public PopupFixTable[] Table { get; set; }
}

[FlatBufferTable, TypeConverter(typeof(ExpandableObjectConverter))]
public class PopupFixTable
{
    [FlatBufferItem(00)] public float EventShowTime { get; set; }
    [FlatBufferItem(01)] public float EventAppearFirstTime { get; set; }
    [FlatBufferItem(02)] public float EventAppearMinTime { get; set; }
    [FlatBufferItem(03)] public float EventAppearMaxTime { get; set; }
    [FlatBufferItem(04)] public int EventPopup1AreaId { get; set; }
    [FlatBufferItem(05)] public int EventPopup2AreaId { get; set; }
    [FlatBufferItem(06)] public int EventPopup3AreaId { get; set; }
    [FlatBufferItem(07)] public int EventPopup4AreaId { get; set; }
    [FlatBufferItem(08)] public float BossShowTime { get; set; }
    [FlatBufferItem(09)] public int BossPopup1AreaId { get; set; }
    [FlatBufferItem(10)] public int BossPopup2AreaId { get; set; }
    [FlatBufferItem(11)] public int BossPopup3AreaId { get; set; }
    [FlatBufferItem(12)] public int BossPopup4AreaId { get; set; }
}
