using System.ComponentModel;
using FlatSharp.Attributes;
// ReSharper disable UnusedMember.Global
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable UnusedType.Global
#nullable disable

namespace pkNX.Structures.FlatBuffers;

// Generated by FlatSharp
// FileIdentifier: 
// FileExtension: 
// Object Count: 2
// Enum Count: 1
// Root Type: GymKooriCourseTableArray

[FlatBufferTable, TypeConverter(typeof(ExpandableObjectConverter))]
public class GymKooriCourseTableArray : IFlatBufferArchive<GymKooriCourseTable>
{
    [FlatBufferItem(0)] public GymKooriCourseTable[] Table { get; set; }
}

[FlatBufferTable, TypeConverter(typeof(ExpandableObjectConverter))]
public class GymKooriCourseTable
{
    [FlatBufferItem(00)] public int CourseId { get; set; }
    [FlatBufferItem(01)] public string SceneName { get; set; }
    [FlatBufferItem(02)] public int ClearTimeMinutes { get; set; }
    [FlatBufferItem(03)] public int ClearTimeSeconds { get; set; }
    [FlatBufferItem(04)] public int ClearTimeMillisecond { get; set; }
    [FlatBufferItem(05)] public int PenaltyTimeMinutes { get; set; }
    [FlatBufferItem(06)] public int PenaltyTimeSeconds { get; set; }
    [FlatBufferItem(07)] public int PenaltyTimeMillisecond { get; set; }
    [FlatBufferItem(08)] public int TimeupTimeMinutes { get; set; }
    [FlatBufferItem(09)] public int TimeupTimeSeconds { get; set; }
    [FlatBufferItem(10)] public int TimeupTimeMillisecond { get; set; }
    [FlatBufferItem(11)] public string BestRecordTimeName { get; set; }
    [FlatBufferItem(12)] public bool ShowNewRecord { get; set; }
    [FlatBufferItem(13)] public bool ShowClearTime { get; set; }
    [FlatBufferItem(14)] public ItemID PrizeItemId { get; set; }
    [FlatBufferItem(15)] public int PrizeItemNum { get; set; }
    [FlatBufferItem(16)] public string IsClearName { get; set; }
    [FlatBufferItem(17)] public ItemID FirstPrizeItemId { get; set; }
    [FlatBufferItem(18)] public int FirstPrizeItemNum { get; set; }
}
