using System.ComponentModel;
using FlatSharp.Attributes;
// ReSharper disable UnusedMember.Global
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable UnusedType.Global
#nullable disable

namespace pkNX.Structures.FlatBuffers;

// Generated by FlatSharp
// FileIdentifier: 
// FileExtension: 
// Object Count: 1
// Enum Count: 0
// Root Type: GymKooriCoursePokemonTable

[FlatBufferTable, TypeConverter(typeof(ExpandableObjectConverter))]
public class GymKooriCoursePokemonTable
{
    [FlatBufferItem(0)] public float MoveSpeed { get; set; }
    [FlatBufferItem(1)] public bool IsPathStartPosition { get; set; }
    [FlatBufferItem(2)] public float NextMoveDuration { get; set; }
    [FlatBufferItem(3)] public float RotationDuration { get; set; }
    [FlatBufferItem(4)] public float MoveSpeedChangeDuration { get; set; }
    [FlatBufferItem(5)] public float BoundPower { get; set; }
}
