using FlatSharp.Attributes;
// ReSharper disable UnusedMember.Global

namespace pkNX.Structures.FlatBuffers;

[FlatBufferEnum(typeof(int))]
public enum PluckEffect
{
    TUIBAMU_NONE = 0,
    TUIBAMU_MAHINAOSI = 1,
    TUIBAMU_NEMUKEZAMASI = 2,
    TUIBAMU_DOKUKESI = 3,
    TUIBAMU_YAKEDONAOSI = 4,
    TUIBAMU_KOORINAOSI = 5,
    TUIBAMU_PPKAIHUKU = 6,
    TUIBAMU_HPKAIHUKU = 7,
    TUIBAMU_KONRANNAOSI = 8,
    TUIBAMU_ZYOUTAIIZYOUNAOSI = 9,
    TUIBAMU_HPKAIHUKUHIRITU = 10,
    TUIBAMU_KARAIKONRAN = 11,
    TUIBAMU_SIBUIKONRAN = 12,
    TUIBAMU_AMAIKONRAN = 13,
    TUIBAMU_NIGAIKONRAN = 14,
    TUIBAMU_SUPPAIKONRAN = 15,
    TUIBAMU_KOUGEKIUP = 16,
    TUIBAMU_BOUGYOUP = 17,
    TUIBAMU_SUBAYASAUP = 18,
    TUIBAMU_TOKUKOUUP = 19,
    TUIBAMU_TOKUBOUUP = 20,
    TUIBAMU_KURITHIKARUUP = 21,
    TUIBAMU_NOURYOKURNDUP = 22,
    TUIBAMU_ITIDODAKEMEITYUUUP = 23,
}
